name: CI

on:
  push:
    branches: [master]

jobs:
  magic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deeps
        run: yarn install

      - name: Check Lint
        run: yarn lint

      - name: Check TS
        run: yarn tsc --noEmit

      - name: Build
        run: yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: out
